import type { Metadata } from "next";
import "@/app/globals.css";
import Image from "next/image";
import { Button } from "@/components/ui/button";
import { Separator } from "@/components/ui/separator";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <header className="w-full h-24 flex justify-center">
          <nav className="container flex justify-between items-center w-full">
            <div className="flex items-center">
              <Image
                src="/1Delhi_Police_Logo.png"
                alt=""
                width={70}
                height={70}
              />
              <h1 className="font-semibold text-xl ml-5">
                Social Media Monitoring of Juvenile Gang Activity
              </h1>
            </div>
            <Link href="/dashboard">
              <Button>Log In</Button>
            </Link>
          </nav>
        </header>
        <Separator />
        <div className="flex flex-1">{children}</div>
      </body>
    </html>
  );
}
